-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Contacts Table (Leads from the website)
create table contacts (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  service_interest text,
  message text,
  status text default 'NEW' -- NEW, CONTACTED, CONVERTED, ARCHIVED
);

-- Jobs Table
create table jobs (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  contact_id uuid references contacts(id),
  status text default 'PENDING', -- PENDING, SCHEDULED, IN_PROGRESS, COMPLETED
  description text,
  quoted_price decimal(10, 2),
  start_time timestamp with time zone,
  end_time_est timestamp with time zone,
  stripe_payment_link text,
  customer_uuid uuid default uuid_generate_v4() -- "Magic Link" access key
);

-- Messages Table (Chat)
create table messages (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  job_id uuid references jobs(id),
  sender_role text not null, -- 'ADMIN' or 'CUSTOMER'
  content text not null,
  is_read boolean default false,
  attachment_url text,
  attachment_type text,
  attachment_name text
);

-- Geolocation Logs Table
create table geolocation_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  job_id uuid references jobs(id),
  latitude double precision not null,
  longitude double precision not null
);

-- Row Level Security (RLS) Policies

-- Contacts: Public can insert (Form), Admin can view all
alter table contacts enable row level security;
create policy "Public can allow insert access to contacts" on contacts for insert with check (true);
create policy "Admin can view all contacts" on contacts for select using (auth.role() = 'authenticated');

-- Jobs: Admin can view/edit all. Customers need logic (Magic Link handled via API usually, or specific RLS if we user Auth)
-- For this "Magic Link" architecture without customer accounts, public access via UUID is often handled at the API layer 
-- or via a special RLS policy if the user is "signing in" anonymously.
-- For simplicity in Phase 2, we will keep RLS strict for Admin and handle Customer access via secure Server Actions / API Routes.
alter table jobs enable row level security;
create policy "Admin full access to jobs" on jobs for all using (auth.role() = 'authenticated');

-- Messages
alter table messages enable row level security;
create policy "Admin full access to messages" on messages for all using (auth.role() = 'authenticated');
create policy "Public can insert messages" on messages for insert with check (true); -- Requires validation in API
create policy "Public can select messages" on messages for select using (true); -- Requires validation in API

-- Geolocation
alter table geolocation_logs enable row level security;
create policy "Admin full access to logs" on geolocation_logs for all using (auth.role() = 'authenticated');
create policy "Public read access to logs" on geolocation_logs for select using (true);
